# modified from https://github.com/toidi/home-kubernetes
- name: Enable memory control group subsystem
  replace:
    path: /boot/cmdline.txt
    regexp: '(rootwait)$'
    replace: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'