# modified from https://github.com/toidi/home-kubernetes

- name: initialize the cluster
  command: sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ master_ip }}
  args:
    creates: /root/cluster_initialized.txt
  register: kubeadm_init_raw

- name: save kubeadm init output to a file
  copy:
    content: "stdout:\n{{ kubeadm_init_raw.stdout }}\n\nstderr:\n{{ kubeadm_init_raw.stderr }}"
    dest: /root/cluster_initialized.txt
  when: kubeadm_init_raw.changed

- name: create .kube directory
  file:
    path: /home/macondo/.kube
    state: directory
    mode: 0755
    owner: macondo
    group: macondo

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/macondo/.kube/config
    remote_src: yes
    owner: macondo
    group: macondo