apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 80
    targetPort: 80  
  selector:
    app: nginx 
  type: NodePort 

---
apiVersion: apps/v1 # apps API group
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec: # Pod spec
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
      # These containers are run during pod initialization
      initContainers:
      - name: install
        image: busybox
        command: ["sh", "-c"]
        args:
        - echo -e "<!doctype html><html><body>" > /work-dir/index.html;
          echo -e "NODE:" $MY_NODE_NAME "POD:" $MY_POD_NAME >>  /work-dir/index.html;
          echo -e "</body></html>" >> /work-dir/index.html;
        volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      dnsPolicy: Default
      volumes:
      - name: workdir
        emptyDir: {}